debug:
  enabled: true
  verbose: datapath
bpf:
  monitorAggregation: none
image:
  repository: quay.io/cilium/cilium-dev
  tag: local
  pullPolicy: IfNotPresent
  useDigest: false
operator:
  enabled: true
  replicas: 1
  image:
    override: ~
    repository: quay.io/cilium/operator
    tag: local
    useDigest: false
    pullPolicy: IfNotPresent
    suffix: ""
encryption:
  enabled: true
  type: ipsec
  ipsec:
    encryptedOverlay: true
envoy:
  enabled: false
enterprise:
 multicast:
    # -- Enables synthetic multicast in cilium, multicast replication works only in tunnel mode.
    enabled: true
