debug:
  enabled: true
  verbose: datapath
bpf:
  monitorAggregation: none
image:
  repository: quay.io/cilium/cilium-dev
  tag: latest
  pullPolicy: IfNotPresent
  useDigest: false
operator:
  enabled: true
  replicas: 1
  image:
    override: ~
    repository: quay.io/cilium/operator
    tag: latest
    useDigest: false
    pullPolicy: IfNotPresent
    suffix: ""
