debug:
  enabled: true
  verbose: datapath
bpf:
  monitorAggregation: none
image:
  repository: quay.io/cilium/cilium-dev
  tag: local_cluster_1
  pullPolicy: IfNotPresent
  useDigest: false
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
operator:
  enabled: true
  replicas: 1
  image:
    override: ~
    repository: quay.io/cilium/operator
    tag: local_cluster_1
    useDigest: false
    pullPolicy: IfNotPresent
    suffix: ""
ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: true
routingMode: tunnel
tunnelProtocol: vxlan
cluster:
  name: cilium-testing-cluster-1
  id: 1
enterprise:
  featureGates: [AllBetaFeatures, AllAlphaFeatures, AllLimitedFeatures]
